### PR TITLE
fix(container-pull-script): allows list tags w/o container runtime

### LINKED ISSUE #369: container-pull-script: look into removing container runtime check for listing tags
As listing tags doesn't require a container runtime - this should be all driven from the API calls, therefore letting a user list tags without having a container runtime.

### PR DESCRIPTION
**Pull request by carlosmmatos**
Fixes #369

This PR allows users to list tags without needed a container runtime. This use-case is valid as we don't require a container runtime to list tags since its based on an API call.

### CODE REVIEW

File: bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh [hunk 1]
```diff
@@ -670,11 +670,6 @@ fi
 #Construct repository path
 REPOSITORY="$cs_registry/$registry_opts/$repository_name"
```
Comment (evanstoner) [inline bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh:671]: `REPOSITORY` needs to be declared before `list_tags` is called since it's used in `print_formatted_tags`:

```
falcon-container-sensor-pull git:(carlosmmatos/issue369) ./falcon-container-sensor-pull.sh --list-tags
WARNING: The default sensor type of falcon-container is deprecated and will be removed in a future release
{
  "name": "falcon-sensor",
  "repository": "",  <-----
  "tags": [
     "6.35.0-1801.container.x86_64.Release.US-2",
...
```

**Review by evanstoner — CHANGES_REQUESTED** [review]

**Review by evanstoner — APPROVED** [review]
