### PR TITLE
fix(container-pull-script): fixes issue with curl errors not being handled properly

### LINKED ISSUE #336: container pull script: handle curl errors
Bash install script has `handle_curl_error()` but the container pull script does not. Ensure we handle timeouts and 400+ HTTP errors (use `curl -f`).

### PR DESCRIPTION
**Pull request by carlosmmatos**
Fixes #336 
Adds error handling for curl similar to our other bash installation scripts. Adds a `-f` option to ensure curl fails and returns a code.

### CODE REVIEW

File: bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh [hunk 1]
```diff
@@ -219,14 +219,45 @@ To bypass this warning, set the optional flag --allow-legacy-curl
...
+handle_curl_error() {
+    local err_msg
+
+    if [ "$1" = "28" ]; then
+        err_msg="Operation timed out (exit code 28). If using a proxy, please check your proxy settings."
+        die "$err_msg"
+    fi
+
+    if [ "$1" = "22" ]; then
+        err_msg="Operation with (exit code 22). The requested URL was not found or returned another error with the HTTP error code being 400 or above."
```
Comment (evanstoner) [inline bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh:232]: Operation _failed_ ~with~ ?

**Review by evanstoner — CHANGES_REQUESTED** [review]

File: bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh (hunk 1 above)
Comment (carlosmmatos) [reply bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh:232]: How'd that happen! ;)
